# Generated by Django 5.2.3 on 2025-07-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.CharField(max_length=100)),
                ('is_normal', models.BooleanField(default=True)),
                ('last_status', models.BooleanField(default=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'unique_together': {('object_type', 'object_id')},
            },
        ),
    ]
